{{
    config(
        unique_key='LISTING_ID'
    )
}}



select LISTING_ID, SCRAPE_ID, SCRAPED_DATE AS DATE, LISTING_NEIGHBOURHOOD, HOST_ID, HOST_NAME, HOST_SINCE, 
HOST_IS_SUPERHOST, HOST_NEIGHBOURHOOD_LGA_CODE, HOST_NEIGHBOURHOOD_LGA_NAME,PROPERTY_TYPE, ROOM_TYPE, PRICE, ACCOMMODATES,
HAS_AVAILABILITY, AVAILABILITY_30, NUMBER_OF_REVIEWS, REVIEW_SCORES_RATING
from {{ ref('listings_stg') }} 