{{
    config(
        unique_key='LISTING_ID'
    )
}}



select LISTING_ID, SCRAPE_ID, SCRAPED_DATE, LISTING_NEIGHBOURHOOD, PRICE, REVIEW_SCORES_RATING, REVIEW_SCORES_ACCURACY, REVIEW_SCORES_CLEANLINESS,
REVIEW_SCORES_CHECKIN, REVIEW_SCORES_COMMUNICATION, REVIEW_SCORES_VALUE
from {{ ref('listings_stg') }} 