sources:
  - name: RAW
    description: Raw data from CSV files
    database: postgres
    schema: RAW

    tables:
      - name: CENSUS_G01
      - name: CENSUS_G02
      - name: listings
      - name: NSW_LGA_SUBURB
      - name: NSW_LGA_CODE
