sources:
  - name: RAW
    description: Raw data from CSV files
    database: postgres
    schema: RAW

    tables:
      - name: listings
      - name: NSW_LGA_SUBURB
      - name: NSW_LGA_CODE
      - name: census_g01
      - name: census_g02