sources:
  - name: postgres
    description: Raw data from CSV files
    database: postgres
    schema: RAW

    tables:
      - name: listings
      - name: NSW_LGA_SUBURB
      - name: NSW_LGA_CODE
      - name: CENSUS_G01
      - name: CENSUS_G02