sources:
  - name: raw
    description: Raw data from CSV files
    database: raw
    schema: raw

    tables:
      - name: CENSUS_G01
      - name: CENSUS_G02
      - name: listings      
      - name: NSW_LGA_CODE
      - name: NSW_LGA_SUBURB
